stages:
  - Build in Release
  - Test
  - Docs

pages:
  stage: Docs
  image: norionomura/jazzy
  tags:
    - docker
  variables:
    MODULE_NAME: "ABCI"
    REPO_URL: "https://gitlab.com/katalysis/cosmosswift/abci"
  script: |
    export VERSION=$(git describe --abbrev=0 --tags || echo "0.0.0")
    swift build
    sourcekitten doc --spm-module "$MODULE_NAME" > "./$MODULE_NAME.json"
    jazzy --clean \
          --author "Alex Tran Qui (ratranqu)" \
          --readme "./README.md" \
          --github_url "$REPO_URL" \
          --github-file-prefix "$REPO_URL/blob/$VERSION" \
          --root-url "https://katalysis.gitlab.io/cosmosswift/abci" \
          --module "$MODULE_NAME" \
          --module-version "$VERSION" \
          --theme docs/theme \
          --sourcekitten-sourcefile "./$MODULE_NAME.json" \
          --output "./public"
  artifacts:
    paths:
      - public

.build:
  stage: Build in Release
  tags:
    - docker
  script:
    - swift build -c release -v

build 5.1:ubuntu-xenial:
  extends: .build
  image: swift:5.1-xenial
build 5.2:ubuntu-xenial:
  extends: .build
  image: norionomura/swift:swift-5.2-branch
build latest:ubuntu-xenial:
  extends: .build
  image: norionomura/swift:nightly
  allow_failure: true

build 5.1:ubuntu-bionic:
  extends: .build
  image: swift:5.1-bionic

.test:
  stage: Test
  tags:
    - docker
  variables:
    PORT: '25667'
  services:
  - name: tendermint/tendermint
    alias: 'tendermint'
    command: [""]
  script:
    - swift build -v
    - swift test

test 5.1:ubuntu-xenial:
  extends: .test
  image: swift:5.1-xenial
test 5.2:ubuntu-xenial:
  extends: .test
  image: norionomura/swift:swift-5.2-branch
test latest:ubuntu-xenial:
  extends: .test
  image: norionomura/swift:nightly
  allow_failure: true

test 5.1:ubuntu-bionic:
  extends: .test
  image: swift:5.1-bionic

